### ISSUE TITLE
Error running 1.5.0

### ISSUE THREAD

**Issue by dogo** [matsoftware/swift-code-metrics#30]
I upgraded to the lastest version and now I can't run 

```python
Traceback (most recent call last):
  File "/usr/local/bin/swift-code-metrics", line 5, in <module>
    from swift_code_metrics.scm import main
  File "/Library/Python/2.7/site-packages/swift_code_metrics/scm.py", line 5, in <module>
    from ._helpers import Log
  File "/Library/Python/2.7/site-packages/swift_code_metrics/_helpers.py", line 12
    def warn(cls, message: str):
                         ^
SyntaxError: invalid syntax
```

**Comment by dogo** [comment]
Duh! I should install using pip3
