### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by sohotj** [matsoftware/swift-code-metrics#8]
~/Deskto: **swift-code-metrics --source SwiftNetFrame --artifacts SwiftNetFrameTest --generate-graphs**
Traceback (most recent call last):
  File "/usr/local/bin/swift-code-metrics", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/scm.py", line 69, in main
    if not analyzer.analyze():
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_analyzer.py", line 21, in analyze
    self.__analyze_directory(self.directory, self.exclude_paths, self.tests_default_suffixes)
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_analyzer.py", line 116, in __analyze_directory
    swift_file = SwiftFileParser(file=full_path, base_path=directory, is_test=is_in_test_path).parse()
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 99, in parse
    framework_name=self.__framework_name(),
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 113, in __framework_name
    return self.__extracted_framework_name() + suffix
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 117, in __extracted_framework_name
    first_subpath = self.__extract_first_subpath(subdir)
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 126, in __extract_first_subpath
    return self.__extract_first_subpath(subdirs[0])
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 126, in __extract_first_subpath
    return self.__extract_first_subpath(subdirs[0])
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 126, in __extract_first_subpath
    return self.__extract_first_subpath(subdirs[0])
  [Previous line repeated 987 more times]
  File "/usr/local/lib/python3.7/site-packages/swift_code_metrics/_parser.py", line 124, in __extract_first_subpath
    subdirs = os.path.split(subdir)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 108, in split
    sep = _get_sep(p)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
**RecursionError: maximum recursion depth exceeded while calling a Python object**

**Comment by matsoftware** [comment]
Can you please post a screenshot of your file system hierarchy?

**Comment by matsoftware** [comment]
Ok I was able to reproduce it locally, working on that now.

**Comment by matsoftware** [comment]
Fixed in https://github.com/matsoftware/swift-code-metrics/pull/10
